/** Labels match legacy application_support.html selects (values map to DB in the action). */

export const NATIONALITY_OPTIONS = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comorian",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "Ecuadorian",
  "Egyptian",
  "Emirati",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Lithuanian",
  "Luxembourgish",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Moldovan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Namibian",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "North Korean",
  "North Macedonian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palestinian",
  "Panamanian",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saudi",
  "Senegalese",
  "Serbian",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Venezuelan",
  "Vietnamese",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
] as const;

export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guinea",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Latvia",
  "Lebanon",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Somalia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export const CURRICULUM_OPTIONS = [
  "IB Diploma",
  "A-Levels",
  "American Diploma",
  "French Baccalaureate",
  "Indian CBSE/ISC",
  "National Curriculum",
  "Other",
] as const;

export const GRADUATION_YEARS = [2026, 2027, 2028] as const;

export type PopularUni = { name: string; loc: string; code: string };

export const POPULAR_UNIVERSITIES: PopularUni[] = [
  { name: "University of Manchester", loc: "Manchester, UK", code: "GB" },
  { name: "University of Toronto", loc: "Toronto, Canada", code: "CA" },
  { name: "King's College London", loc: "London, UK", code: "GB" },
  { name: "University of Edinburgh", loc: "Edinburgh, UK", code: "GB" },
  { name: "UCL", loc: "London, UK", code: "GB" },
  { name: "McGill University", loc: "Montreal, Canada", code: "CA" },
  { name: "University of Warwick", loc: "Coventry, UK", code: "GB" },
  { name: "University of Bristol", loc: "Bristol, UK", code: "GB" },
  { name: "University of Bath", loc: "Bath, UK", code: "GB" },
  { name: "University of Waterloo", loc: "Waterloo, Canada", code: "CA" },
  { name: "NYU", loc: "New York, USA", code: "US" },
  { name: "American University of Beirut", loc: "Beirut, Lebanon", code: "LB" },
  { name: "UBC", loc: "Vancouver, Canada", code: "CA" },
  { name: "University of Leeds", loc: "Leeds, UK", code: "GB" },
  { name: "Boston University", loc: "Boston, USA", code: "US" },
];

export const PACK_PRICES: Record<5 | 10 | 15, number> = {
  5: 2000,
  10: 3500,
  15: 5000,
};

/** Chips — application_support vf.html */
export const VF_DESTINATION_CHIPS = [
  "United States",
  "United Kingdom",
  "Canada",
  "Europe",
  "Australia",
  "UAE / GCC",
  "Not sure yet",
] as const;

export const VF_APPLY_TIMING_CHIPS = ["This year", "Next year", "Not sure yet"] as const;

export const VF_GRADE_YEAR_OPTIONS = [
  "Grade 10",
  "Grade 11",
  "Grade 12",
  "Gap year",
  "Already graduated",
] as const;

/** Datalist suggestions — vf.html */
export const VF_FIELD_OF_STUDY_SUGGESTIONS = [
  "Business & Management",
  "Computer Science",
  "Engineering — Mechanical",
  "Engineering — Electrical",
  "Engineering — Civil",
  "Engineering — Chemical",
  "Engineering — Biomedical",
  "Medicine",
  "Dentistry",
  "Pharmacy",
  "Nursing",
  "Law",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "International Relations",
  "Political Science",
  "Psychology",
  "Sociology",
  "Architecture",
  "Interior Design",
  "Graphic Design",
  "Fine Arts",
  "Film & Media",
  "Journalism",
  "Communications",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Data Science",
  "Artificial Intelligence",
  "Cybersecurity",
  "Environmental Science",
  "Education",
  "Hospitality & Tourism",
  "Aviation",
  "Not sure yet",
] as const;

export const VF_JOURNEY_STEPS = [
  "Tell us about your goals",
  "Choose your application strategy",
  "Share your universities — or ask us to help",
  "Upload anything you already have",
  "Book your onboarding session",
  "Get your personalized support plan",
  "Continue with the package that fits you",
] as const;

export const VF_INCLUDED_COMPACT = [
  "Personalized university strategy",
  "Essay brainstorming & review",
  "Application guidance & checks",
  "CV & document feedback",
  "Deadline planning",
  "Scholarship support",
  "Visa & next steps guidance",
  "Ongoing advisor touchpoints",
  "Student community connections",
] as const;
